// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyiwP4jcuNCeri7MIGA_9HIkZZYn1YWJM',
    appId: '1:951709762235:web:d24ece38ed5d1dddd31f9e',
    messagingSenderId: '951709762235',
    projectId: 'joonyerconnect',
    authDomain: 'joonyerconnect.firebaseapp.com',
    databaseURL: 'https://joonyerconnect-default-rtdb.firebaseio.com',
    storageBucket: 'joonyerconnect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZLCIhiZYJnR_-3pkZfmnF5GczUHvb6DU',
    appId: '1:951709762235:android:d6e19c5f22d7a2cbd31f9e',
    messagingSenderId: '951709762235',
    projectId: 'joonyerconnect',
    databaseURL: 'https://joonyerconnect-default-rtdb.firebaseio.com',
    storageBucket: 'joonyerconnect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW1PDVa8Zg0v1f2ccWAPvh5jsdYJyn8nc',
    appId: '1:951709762235:ios:c4a3bb35a9ef1982d31f9e',
    messagingSenderId: '951709762235',
    projectId: 'joonyerconnect',
    databaseURL: 'https://joonyerconnect-default-rtdb.firebaseio.com',
    storageBucket: 'joonyerconnect.appspot.com',
    iosBundleId: 'com.example.minimal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW1PDVa8Zg0v1f2ccWAPvh5jsdYJyn8nc',
    appId: '1:951709762235:ios:c4a3bb35a9ef1982d31f9e',
    messagingSenderId: '951709762235',
    projectId: 'joonyerconnect',
    databaseURL: 'https://joonyerconnect-default-rtdb.firebaseio.com',
    storageBucket: 'joonyerconnect.appspot.com',
    iosBundleId: 'com.example.minimal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyiwP4jcuNCeri7MIGA_9HIkZZYn1YWJM',
    appId: '1:951709762235:web:1155b5720f3d95c3d31f9e',
    messagingSenderId: '951709762235',
    projectId: 'joonyerconnect',
    authDomain: 'joonyerconnect.firebaseapp.com',
    databaseURL: 'https://joonyerconnect-default-rtdb.firebaseio.com',
    storageBucket: 'joonyerconnect.appspot.com',
  );

}